version: "3.7"
services:
  transaction-server:
    container_name: transaction-server
    build: .
    restart: always
    depends_on:
      - mongo_db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8083:8083"
  mongo_db:
    image: "mongo:5.0.1"
    restart: always
    ports:
      - "27021:27017"
networks:
  default:
    name: custom-network