spring:
  config:
    import: optional:configserver:http://config-server:7000
  cloud:
    config:
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
