spring:
  config:
    import: optional:configserver:http://config-server-svc
  cloud:
    config:
      profile: prod

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}